#!/usr/bin/env bash
# yahboom_find_port.sh — discover the YB-ERF01's stable /dev/serial/by-path
# entry by checking which CH340 actually responds to FUNC_VERSION.
#
# Why: when both the YB-ERF01 and the WitMotion (also CH340 1a86:7523) are
# on the bus, /dev/myserial races between them. /dev/serial/by-path/*
# entries are auto-generated by the kernel from physical USB port paths
# and are stable per port — but with two CH340s, you still need to know
# WHICH one is the YB-ERF01. We test each by trying to read firmware
# version; only the YB-ERF01 will respond.
#
# Usage:
#   ./scripts/yahboom_find_port.sh
#   # On success, writes the path to ~/.yahboom_serial_port and prints it.
#
# After success, ./start_yahboom.sh picks it up automatically.

set -euo pipefail

CFG_FILE="$HOME/.yahboom_serial_port"

# Find every CH340 USB-Serial via stable by-path symlinks
mapfile -t BY_PATH_LINKS < <(
  for link in /dev/serial/by-path/*; do
    [ -e "$link" ] || continue
    target="$(readlink -f "$link")"
    if udevadm info -q property "$target" 2>/dev/null | grep -q "ID_VENDOR_ID=1a86"; then
      echo "$link"
    fi
  done
)

if [ ${#BY_PATH_LINKS[@]} -eq 0 ]; then
  echo "ERROR: no CH340 USB-Serial devices found. Plug in the YB-ERF01."
  exit 1
fi

echo "Found ${#BY_PATH_LINKS[@]} CH340 by-path entries:"
printf '  %s\n' "${BY_PATH_LINKS[@]}"
echo

probe_port() {
  local port="$1"
  python3 - "$port" <<'PY'
import sys, time
try:
    from Rosmaster_Lib import Rosmaster
except ModuleNotFoundError:
    sys.exit("Rosmaster_Lib not installed — run install.sh")
port = sys.argv[1]
try:
    bot = Rosmaster(car_type=1, com=port)
    bot.create_receive_threading()
    time.sleep(0.4)
    v = bot.get_version()
    print(f"  → firmware version: {v}")
    sys.exit(0 if v not in (-1, 0) else 1)
except Exception as e:
    print(f"  → open failed: {e}")
    sys.exit(2)
PY
}

WINNER=""
for link in "${BY_PATH_LINKS[@]}"; do
  echo "Probing $link ..."
  if probe_port "$link"; then
    WINNER="$link"
    break
  fi
done

if [ -z "$WINNER" ]; then
  echo
  echo "ERROR: none of the CH340 ports responded to FUNC_VERSION."
  echo "Check: USB-C is the data port (not power-only), no other process"
  echo "is holding the serial (./kill_yahboom.sh), and the YB-ERF01 is"
  echo "powered on."
  exit 2
fi

echo
echo "YB-ERF01 found at: $WINNER"
echo "$WINNER" > "$CFG_FILE"
echo "Wrote $CFG_FILE — ./start_yahboom.sh will use it automatically."
