#!/usr/bin/env bash
# yahboom_find_port.sh — discover the YB-ERF01's stable /dev/serial/by-path
# entry by sending a beep to each candidate CH340 and asking which one
# actually beeped.
#
# Why: when both the YB-ERF01 and the WitMotion (also CH340 1a86:7523) are
# on the bus, /dev/myserial races between them. /dev/serial/by-path/*
# entries are auto-generated by the kernel from physical USB port paths
# and are stable per port — but with two CH340s, you still need to know
# WHICH one is the YB-ERF01.
#
# We use a one-way beep packet (FUNC_BEEP = 0x02) instead of reading
# FUNC_VERSION because some YB-ERF01 firmware revisions — especially with
# auto-report disabled in flash — accept commands fine but never respond
# to FUNC_REQUEST_DATA. The beep is audible, irrefutable, and survives
# even a totally muted RX line. The WitMotion ignores Yahboom protocol
# bytes entirely, so it stays silent.
#
# Usage:
#   ./scripts/yahboom_find_port.sh
#
# Listen for which port produces a beep, type the path number when
# prompted, and the script writes it to ~/.yahboom_serial_port.
# ./start_yahboom.sh picks that up automatically.

set -euo pipefail

CFG_FILE="$HOME/.yahboom_serial_port"

# Find every CH340 USB-Serial via stable by-path symlinks
mapfile -t BY_PATH_LINKS < <(
  for link in /dev/serial/by-path/*; do
    [ -e "$link" ] || continue
    target="$(readlink -f "$link")"
    if udevadm info -q property "$target" 2>/dev/null | grep -q "ID_VENDOR_ID=1a86"; then
      echo "$link"
    fi
  done
)

if [ ${#BY_PATH_LINKS[@]} -eq 0 ]; then
  echo "ERROR: no CH340 USB-Serial devices found. Plug in the YB-ERF01."
  exit 1
fi

echo "Found ${#BY_PATH_LINKS[@]} CH340 by-path entries:"
printf '  %s\n' "${BY_PATH_LINKS[@]}"
echo

beep_port() {
  local port="$1"
  python3 - "$port" <<'PY'
import sys, time, serial
port = sys.argv[1]
HEAD, DEVICE_ID, COMPLEMENT = 0xFF, 0xFC, 1   # 257 - 0xFC
FUNC_BEEP = 0x02
val = (300).to_bytes(2, 'little')              # 300 ms beep — long enough to hear clearly
cmd = [HEAD, DEVICE_ID, 0x05, FUNC_BEEP, val[0], val[1]]
chk = (sum(cmd) + COMPLEMENT) & 0xFF
cmd.append(chk)
try:
    s = serial.Serial(port, 115200, timeout=0.2)
    s.write(bytes(cmd))
    s.flush()
    time.sleep(0.5)
    s.close()
except Exception as e:
    print(f"  → open/write failed: {e}", file=sys.stderr)
    sys.exit(1)
PY
}

echo "Sending a 300 ms beep to each port. Listen carefully."
echo "Tip: the YB-ERF01 buzzer is mounted near the USB-C ports."
echo

declare -a BEEPED
for i in "${!BY_PATH_LINKS[@]}"; do
  link="${BY_PATH_LINKS[$i]}"
  echo "[$((i+1))/${#BY_PATH_LINKS[@]}] Beeping $link ..."
  beep_port "$link" || true
  sleep 1.0   # space the beeps so the user can tell them apart
done

echo
echo "Which beep number did you hear (1-${#BY_PATH_LINKS[@]}, or 'r' to retry, or '0' for none)?"
read -r CHOICE

case "$CHOICE" in
  r|R)
    exec "$0" ;;
  0|"")
    echo
    echo "ERROR: no beep heard. The YB-ERF01 is not communicating."
    echo "Verify in order:"
    echo "  1. The USB-C cable is in the *data* port on the board (not power-only)."
    echo "  2. Cable is data-capable (some USB-C cables are charge-only)."
    echo "  3. Buzzer isn't disabled — try 'sudo dmesg | tail' for any USB errors."
    echo "  4. Board has 24 V motor power if it requires it for buzzer."
    echo "  5. Re-flash factory defaults: python3 scripts/yahboom_configure.py --factory-reset"
    echo "     (run with /dev/serial/by-path/<port> using --port <path>)"
    exit 2
    ;;
  *)
    if ! [[ "$CHOICE" =~ ^[0-9]+$ ]] || [ "$CHOICE" -lt 1 ] || [ "$CHOICE" -gt ${#BY_PATH_LINKS[@]} ]; then
      echo "Invalid choice: $CHOICE"; exit 1
    fi
    WINNER="${BY_PATH_LINKS[$((CHOICE-1))]}"
    ;;
esac

echo
echo "YB-ERF01 → $WINNER"
echo "$WINNER" > "$CFG_FILE"
echo "Wrote $CFG_FILE — ./start_yahboom.sh will use it automatically."
